baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-leaflet'

[module]
  replacements = 'github.com/oolonek/mod-leaflet -> ../..'
  [[module.imports]]
    path = "github.com/oolonek/mod-leaflet"
  [[module.imports.mounts]]
    source = "data"
    target = "data"
  [[module.imports.mounts]]
    source = "dist"
    target = "static"
  [[module.imports.mounts]]
    source = "static"
    target = "static"
  [[module.imports.mounts]]
    source = "dist/leaflet.scss"
    target = "static/leaflet.css"
  [[module.imports.mounts]]
    source = "dist/MarkerCluster.css"
    target = "static/MarkerCluster.css"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.imports.mounts]]
    source = "assets/js/modules/leaflet/leaflet-map.js"
    target = "static/leaflet-map.js"
  [[module.imports.mounts]]
    source = "assets/js/modules/leaflet/leaflet-mapcluster.js"
    target = "static/leaflet-mapcluster.js"
